- name: 'Build and run Docker image'
  hosts: localhost
  tasks:
    - name: Build Docker image
      command: 'docker build -t arwebcs/abctech .'
    
    - name: Run in container
      command: 'docker run -d --rm --name "purdue-igp" -p 8081:8080 arwebcs/abctech'      
   
